name: pytest
on: 
  push:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  test:
    strategy:
      matrix:
        py-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}

      - name: Install develop dependencies
        run: pip install .[develop]
        
      - name: Run test suite
        run: pytest
